//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vangeneugden_Robin_DMP_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groep()
        {
            this.GroepOptreden = new HashSet<GroepOptreden>();
            this.GroepRepetitie = new HashSet<GroepRepetitie>();
            this.LidGroep = new HashSet<LidGroep>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public string omschrijving { get; set; }
        public bool externeGroep { get; set; }
        public Nullable<int> dirigentId { get; set; }
    
        public virtual Lid Lid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroepOptreden> GroepOptreden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroepRepetitie> GroepRepetitie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LidGroep> LidGroep { get; set; }

        public override string ToString()
        {
            return naam;
        }
    }
}
