//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vangeneugden_Robin_DMP_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.LidInstrument = new HashSet<LidInstrument>();
        }
    
        public int id { get; set; }
        public string artikelNummer { get; set; }
        public string naam { get; set; }
        public string soort { get; set; }
        public string omschrijving { get; set; }
        public Nullable<System.DateTime> bouwjaar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LidInstrument> LidInstrument { get; set; }

        public override string ToString()
        {
            return naam;
        }
    }
}
